project_name: nib
# go build configuration
builds:
  - id: cli
    env: [CGO_ENABLED=0]
    dir: cli
    binary: nib
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: srv
    env: [CGO_ENABLED=0]
    binary: srv
    dir: srv
    main: ./cmd/srv
    goos:
      - linux
    goarch:
      - amd64
      - arm64
# verifiable builds
gomod:
  proxy: true
  env:
    - GOPROXY=https://prism.v2.dcas.dev/api/go,https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
  mod: mod

# generate archives for the CLI
archives:
  - format: tar.gz
    builds:
      - cli
    wrap_in_directory: false
    files:
      - LICENCE
# generate container images
kos:
  - id: default
    repository: ghcr.io/djcass44/nib/srv
    build: srv
    working_dir: srv
    main: ./cmd/srv/...
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - latest
      - "{{ .Tag }}"
    sbom: cyclonedx
    ko_data_creation_time: ''
    creation_time: ''
    bare: true
    preserve_import_paths: false
  - id: debug
    repository: ghcr.io/djcass44/nib/srv-debug
    base_image: cgr.dev/chainguard/busybox
    build: srv
    working_dir: srv
    main: ./cmd/srv/...
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - latest
      - "{{ .Tag }}"
    sbom: cyclonedx
    ko_data_creation_time: ''
    creation_time: ''
    bare: true
    preserve_import_paths: false